export const simulatorCopy = {
  en: {
    title: "Local simulator",
    run: "Start",
    pause: "Pause",
    step: "Step (10 ms)",
    stop: "Stop",
    reset: "Reset",
    rebuild: "Recompile",
    save: "Save scene",
    close: "Close simulator",
    expand: "Expand workspace",
    showEditor: "Show editor",
    speed: "Speed",
    preparing: "Compiling robot programs…",
    ready: "Setup",
    running: "Running",
    paused: "Paused",
    stopped: "Stopped",
    completed: "Completed",
    error: "Simulation error",
    mode: "Mode",
    practice: "Practice",
    match: "Match",
    seed: "Random seed",
    randomize: "Apply seed",
    newSeed: "New seed & balls",
    duration: "Duration (s)",
    field: "WRO Double Tennis 2026 field",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    fit: "Fit field",
    trace: "Trails",
    rays: "Sensor rays",
    headings: "Headings",
    collisions: "Collision hints",
    restrictedZones: "Restricted zones",
    setupHint:
      "Drag robots and balls. Drag empty space to pan; scroll to zoom. Editing a running scene resets it.",
    config: "Robot setup",
    inspector: "Live inspector",
    events: "Events",
    selected: "Selected robot",
    addRobot: "Add robot",
    removeRobot: "Remove robot",
    robotName: "Name",
    controller: "Controller",
    controllerSource: "Controller source",
    program: "Project program",
    builtin: "Built-in opponent",
    builtinLevels: {
      easy: "Built-in opponent · Easy",
      standard: "Built-in opponent · Standard",
      hard: "Built-in opponent · Hard",
    },
    disabled: "Disabled",
    drive: "Drive",
    differential: "Differential",
    omni3: "3-wheel omni",
    omni4: "4-wheel omni",
    pose: "Start position",
    x: "X (mm)",
    y: "Y (mm)",
    heading: "Heading (°)",
    body: "Body",
    width: "Width (mm)",
    length: "Length (mm)",
    mass: "Mass (kg)",
    wheels: "Wheels",
    wheelTraction: "Wheel collision behavior",
    wheelSlip: "Spin when blocked",
    wheelGrip: "Stop when blocked (approximate)",
    port: "Port",
    angle: "Angle (°)",
    diameter: "Diameter (mm)",
    gear: "Gear ratio",
    inverted: "Reverse direction",
    sensors: "Sensors",
    addSensor: "Add sensor",
    remove: "Remove",
    kind: "Kind",
    color: "Color",
    ultrasonic: "Ultrasonic",
    gyro: "Gyro",
    touch: "Touch",
    vision: "Vision",
    pixy2: "Pixy2 camera (LEGO)",
    cameraHeight: "Camera height (mm)",
    cameraPitch: "Camera tilt (°)",
    verticalFov: "Vertical view (°)",
    orangeSignature: "Orange signature",
    purpleSignature: "Purple signature",
    untrained: "Not trained",
    pixy2Hint:
      "LEGO I2C color blocks only. Read registers 81–87 at address 1 for count, X, Y, width and height (0–255). X points right; Y points down. Tilt is positive upward. No line tracking, RGB or video.",
    pixy2SignatureHint:
      "Signatures model trained ball colors. Choose Not trained to hide a color; distance is inferred from block size, not returned directly.",
    range: "Range (mm)",
    fov: "Field of view (°)",
    pusher: "Pusher",
    depth: "Depth (mm)",
    shooter: "Shooter",
    elevation: "Elevation (°)",
    stroke: "Stroke (°)",
    shotSpeed: "Ball speed (mm/s)",
    noShooterPort: "Four-wheel drive uses all four motor ports.",
    details: "Execution",
    lcd: "Robot LCD",
    variables: "Global variables",
    locals: "Local variables",
    motors: "Motors",
    source: "Show source",
    noProgram: "No project entry available",
    noData: "Start or step to inspect a robot.",
    elapsed: "Time",
    distance: "Distance",
    chassisHeight: "Base height",
    score: "Score",
    continued: "Continuing practice · provisional score",
    buttons: "EV3 buttons",
    up: "Up",
    down: "Down",
    left: "Left",
    right: "Right",
    enter: "Enter",
    back: "Back",
    saved: "Scene saved",
    saveFailed: "Could not save scene",
    errorHint: "Correct the program, then press Start to run it again.",
    disclaimer:
      "Physics, sensors, vision, trajectories and judging are approximate. This is a practice tool, not an official referee or a substitute for hardware testing.",
    snapshotHint:
      "Start saves and compiles changed programs and resources automatically. Changing setup resets the scene.",
    shortened: "Variable previews are shortened to keep the simulator responsive.",
    balls: "Balls",
    selectedBall: "Selected ball",
    orange: "Orange",
    purple: "Purple",
    height: "Height (mm)",
    noEvents: "No events yet",
    instructions: "Instructions",
    status: "Status",
    setupRequired: "Reset to edit setup",
    programLocation: "Program location",
    customName: "Sensor name",
    invalidNumber: "Enter a finite number in range.",
    keyboardHint:
      "Hold a button with the pointer or Space / Enter. Arrow keys work while the pad has focus.",
    scene: "Scene",
    layers: "Layers",
    robots: "Robots",
    fieldHint:
      "Drag to move · drag the round handle to rotate (Shift snaps 15°) · arrow keys nudge, Q / E rotate · scroll to zoom, double-click to fit",
    noBall: "Click a ball on the field to edit its start position and height.",
    about: "About the simulator",
    allEvents: "All",
    info: "Info",
    collision: "Collision",
    violation: "Violation",
    scoreEvent: "Score",
    errorEvent: "Error",
    callStack: "Call stack",
    position: "Position",
    basics: "Basics",
    team: "Team",
    teamA: "Team A",
    teamB: "Team B",
    fieldLabel: "Field",
    fieldPractice: "Practice mat",
    fieldWro: "WRO Double Tennis 2026",
    switchFieldTitle: "Switch field?",
    switchFieldBody:
      "The current scene has unsaved changes. Switching replaces it with the default scene for the other field.",
    switchFieldConfirm: "Switch field",
    cancel: "Cancel",
    resetForSettings: "Scene reset to apply the new setup.",
    staleProgram: "Program changed — press Start to run the new version.",
    portWarningsTitle: "The program uses ports this robot does not have",
    portMotorMissing: (port: string) =>
      `Motor ${port} is used, but no wheel or shooter is on ${port}.`,
    portSensorMissing: (port: string) =>
      `Sensor port ${port} is read, but no sensor is configured.`,
    openSetup: "Open robot setup",
    preset: "Robot preset",
    presetDrivingBase: "Driving Base (Education)",
    presetWro: "WRO default robot",
    presetCustom: "Custom",
    advanced: "Advanced",
    driveLeft: "Left motor",
    driveRight: "Right motor",
    sensorPort: (port: number) => `Port ${port}`,
    noSensor: "None",
    elapsedOnly: "Elapsed time",
  },
  "zh-TW": {
    title: "本地模擬器",
    run: "開始",
    pause: "暫停",
    step: "單步 (10ms)",
    stop: "停止",
    reset: "重置",
    rebuild: "重新編譯",
    save: "儲存場景",
    close: "關閉模擬器",
    expand: "展開工作區",
    showEditor: "顯示程式編輯器",
    speed: "速度",
    preparing: "正在編譯機器人程式…",
    ready: "設定中",
    running: "執行中",
    paused: "已暫停",
    stopped: "已停止",
    completed: "已結束",
    error: "模擬錯誤",
    mode: "模式",
    practice: "練習",
    match: "比賽",
    seed: "亂數種子",
    randomize: "套用種子",
    newSeed: "新種子與球位",
    duration: "時間（秒）",
    field: "WRO Double Tennis 2026 場地",
    zoomIn: "放大",
    zoomOut: "縮小",
    fit: "符合場地",
    trace: "軌跡",
    rays: "感測射線",
    headings: "朝向",
    collisions: "碰撞提示",
    restrictedZones: "限制區域",
    setupHint: "可拖動機器人及球。拖動空白處平移，滾輪縮放；修改執行中的場景會自動重置。",
    config: "機器人設定",
    inspector: "即時檢視",
    events: "事件",
    selected: "選取機器人",
    addRobot: "加入機器人",
    removeRobot: "移除機器人",
    robotName: "名稱",
    controller: "控制器",
    controllerSource: "控制來源",
    program: "專案程式",
    builtin: "內建對手",
    builtinLevels: {
      easy: "內建對手 · 簡易",
      standard: "內建對手 · 標準",
      hard: "內建對手 · 困難",
    },
    disabled: "停用",
    drive: "驅動",
    differential: "差速驅動",
    omni3: "三輪全向",
    omni4: "四輪全向",
    pose: "起始位置",
    x: "X（mm）",
    y: "Y（mm）",
    heading: "朝向（°）",
    body: "車身",
    width: "寬度（mm）",
    length: "長度（mm）",
    mass: "質量（kg）",
    wheels: "輪組",
    wheelTraction: "輪胎碰撞行為",
    wheelSlip: "碰撞時空轉",
    wheelGrip: "碰撞時輪子停轉（近似）",
    port: "埠",
    angle: "角度（°）",
    diameter: "直徑（mm）",
    gear: "齒輪比",
    inverted: "反轉方向",
    sensors: "感測器",
    addSensor: "加入感測器",
    remove: "移除",
    kind: "種類",
    color: "顏色",
    ultrasonic: "超音波",
    gyro: "陀螺儀",
    touch: "觸碰",
    vision: "視覺",
    pixy2: "Pixy2 相機（LEGO）",
    cameraHeight: "相機高度（mm）",
    cameraPitch: "相機俯仰（°）",
    verticalFov: "垂直視角（°）",
    orangeSignature: "橘球色碼",
    purpleSignature: "紫球色碼",
    untrained: "未訓練",
    pixy2Hint:
      "僅模擬 LEGO I2C 色塊辨識。在位址 1 讀取暫存器 81–87，取得數量、X、Y、寬及高（0–255）。X 向右、Y 向下，俯仰正值朝上。不支援巡線、RGB 或影片。",
    pixy2SignatureHint:
      "色碼代表訓練過的球色。選擇「未訓練」可忽略該色；距離需由色塊大小估算，不直接回傳。",
    range: "範圍（mm）",
    fov: "視角（°）",
    pusher: "推球板",
    depth: "深度（mm）",
    shooter: "發射器",
    elevation: "仰角（°）",
    stroke: "行程（°）",
    shotSpeed: "球速（mm/s）",
    noShooterPort: "四輪驅動已使用所有馬達埠。",
    details: "執行詳情",
    lcd: "機器人 LCD",
    variables: "全域變數",
    locals: "區域變數",
    motors: "馬達",
    source: "查看原始碼",
    noProgram: "尚無可用的專案入口",
    noData: "開始或單步後可檢視機器人。",
    elapsed: "時間",
    distance: "距離",
    chassisHeight: "車身底部高度",
    score: "分數",
    continued: "繼續練習 · 分數為暫定",
    buttons: "EV3 按鈕",
    up: "上",
    down: "下",
    left: "左",
    right: "右",
    enter: "確認",
    back: "返回",
    saved: "場景已儲存",
    saveFailed: "無法儲存場景",
    errorHint: "修正程式後按「開始」重新執行。",
    disclaimer:
      "物理、感測器、視覺、拋射軌跡與判分皆為近似模型。這是練習工具，不能取代官方裁判或實機驗證。",
    snapshotHint: "按「開始」時會自動儲存並編譯有變更的程式及素材；修改設定會自動重置場景。",
    shortened: "變數預覽已縮短，以保持介面流暢。",
    balls: "球",
    selectedBall: "選取的球",
    orange: "橘色",
    purple: "紫色",
    height: "高度（mm）",
    noEvents: "尚無事件",
    instructions: "指令數",
    status: "狀態",
    setupRequired: "重設後即可修改設定",
    programLocation: "程式位置",
    customName: "感測器名稱",
    invalidNumber: "請輸入範圍內的有限數字。",
    keyboardHint: "以滑鼠或空白鍵／Enter 按住按鈕。焦點在按鈕區時也可使用方向鍵。",
    scene: "場景",
    layers: "圖層",
    robots: "機器人",
    fieldHint:
      "拖動可移動 · 拖動圓形把手可旋轉（Shift 以 15° 對齊）· 方向鍵微調、Q／E 旋轉 · 滾輪縮放、雙擊符合場地",
    noBall: "點選場地上的球，即可修改起始位置與高度。",
    about: "關於模擬器",
    allEvents: "全部",
    info: "訊息",
    collision: "碰撞",
    violation: "違規",
    scoreEvent: "得分",
    errorEvent: "錯誤",
    callStack: "呼叫堆疊",
    position: "位置",
    basics: "基本",
    team: "隊伍",
    teamA: "A 隊",
    teamB: "B 隊",
    fieldLabel: "場地",
    fieldPractice: "練習場地",
    fieldWro: "WRO Double Tennis 2026",
    switchFieldTitle: "要切換場地嗎？",
    switchFieldBody: "目前的場景有未儲存的修改。切換後會改用另一個場地的預設場景。",
    switchFieldConfirm: "切換場地",
    cancel: "取消",
    resetForSettings: "已重置場景以套用設定。",
    staleProgram: "程式已修改，按「開始」以新程式重新執行。",
    portWarningsTitle: "程式用到這台機器人沒有的端口",
    portMotorMissing: (port: string) => `程式用到馬達 ${port}，但 ${port} 沒有接輪子或發射器。`,
    portSensorMissing: (port: string) => `程式讀取感測器端口 ${port}，但該端口沒有設定感測器。`,
    openSetup: "開啟機器人設定",
    preset: "機器人預設",
    presetDrivingBase: "Driving Base（教育版）",
    presetWro: "WRO 預設機器人",
    presetCustom: "自訂",
    advanced: "進階",
    driveLeft: "左馬達",
    driveRight: "右馬達",
    sensorPort: (port: number) => `端口 ${port}`,
    noSensor: "無",
    elapsedOnly: "經過時間",
  },
} as const;
export type SimulatorLocale = keyof typeof simulatorCopy;
export type SimulatorCopy = (typeof simulatorCopy)[SimulatorLocale];
