/** Reviewed names for the pinned Monaco command catalog. IDs remain stable across locales. */
export const COMMAND_LABELS: Record<string, readonly [en: string, zh: string]> = {
  _lastCursorMoveToSelect: ["Move last cursor and extend selection", "移動最後一個游標並延伸選取"],
  _lineSelect: ["Select line", "選取整行"],
  _lineSelectDrag: ["Drag to select lines", "拖曳選取整行"],
  _moveTo: ["Move to position", "移動至指定位置"],
  _moveToSelect: ["Move to position and extend selection", "移動至指定位置並延伸選取"],
  _wordSelect: ["Select word", "選取單字"],
  _wordSelectDrag: ["Drag to select words", "拖曳選取單字"],
  acceptAlternativeSelectedSuggestion: [
    "Accept selected suggestion with alternative insertion",
    "以替代方式接受選取的建議",
  ],
  acceptRenameInput: ["Confirm rename", "確認重新命名"],
  acceptRenameInputWithPreview: ["Preview rename", "預覽重新命名"],
  acceptSelectedCodeAction: ["Apply selected code action", "套用選取的程式碼動作"],
  acceptSelectedSuggestion: ["Accept selected suggestion", "接受選取的建議"],
  acceptSnippet: ["Finish snippet", "完成程式碼片段"],
  "actions.find": ["Find", "搜尋"],
  "actions.findWithSelection": ["Find With Selection", "搜尋選取文字"],
  cancelLinkedEditingInput: ["Cancel linked editing", "取消連動編輯"],
  cancelRenameInput: ["Cancel rename", "取消重新命名"],
  cancelSelection: ["Cancel selection", "取消選取"],
  closeFindWidget: ["Close find widget", "關閉搜尋視窗"],
  closeMarkersNavigation: ["Close diagnostics navigation", "關閉診斷導覽"],
  closeParameterHints: ["Close parameter hints", "關閉參數提示"],
  closeReferenceSearch: ["Close reference search", "關閉參考搜尋"],
  "codelens.showLensesInCurrentLine": [
    "Show CodeLens Commands For Current Line",
    "顯示目前行的 CodeLens 命令",
  ],
  columnSelect: ["Select rectangular block", "選取矩形區塊"],
  createCursor: ["Create cursor", "新增游標"],
  cursorBottom: ["Move cursor to document bottom", "將游標移至文件底部"],
  cursorBottomSelect: ["Select to document bottom", "選取至文件底部"],
  cursorColumnSelectDown: ["Extend column selection down", "向下延伸矩形選取"],
  cursorColumnSelectLeft: ["Extend column selection left", "向左延伸矩形選取"],
  cursorColumnSelectPageDown: ["Extend column selection down one page", "向下延伸一頁的矩形選取"],
  cursorColumnSelectPageUp: ["Extend column selection up one page", "向上延伸一頁的矩形選取"],
  cursorColumnSelectRight: ["Extend column selection right", "向右延伸矩形選取"],
  cursorColumnSelectUp: ["Extend column selection up", "向上延伸矩形選取"],
  cursorDown: ["Move cursor to next line", "將游標移至下一行"],
  cursorDownSelect: ["Select to next line", "選取至下一行"],
  cursorEnd: ["Move cursor to end of line", "將游標移至行尾"],
  cursorEndSelect: ["Select to end of line", "選取至行尾"],
  cursorHome: [
    "Move cursor to line start or first non-whitespace character",
    "將游標移至行首或第一個非空白字元",
  ],
  cursorHomeSelect: [
    "Select to line start or first non-whitespace character",
    "選取至行首或第一個非空白字元",
  ],
  cursorLeft: ["Move cursor to previous character", "將游標移至左側字元"],
  cursorLeftSelect: ["Select to previous character", "選取至左側字元"],
  cursorLineEnd: ["Move cursor to end of logical line", "將游標移至實際行尾"],
  cursorLineEndSelect: ["Select to end of logical line", "選取至實際行尾"],
  cursorLineStart: ["Move cursor to start of logical line", "將游標移至實際行首"],
  cursorLineStartSelect: ["Select to start of logical line", "選取至實際行首"],
  cursorMove: ["Move cursor with options", "依指定方式移動游標"],
  cursorPageDown: ["Move cursor to next page", "將游標移至下一頁"],
  cursorPageDownSelect: ["Select to next page", "選取至下一頁"],
  cursorPageUp: ["Move cursor to previous page", "將游標移至上一頁"],
  cursorPageUpSelect: ["Select to previous page", "選取至上一頁"],
  cursorRedo: ["Cursor Redo", "重做游標移動"],
  cursorRight: ["Move cursor to next character", "將游標移至右側字元"],
  cursorRightSelect: ["Select to next character", "選取至右側字元"],
  cursorTop: ["Move cursor to document top", "將游標移至文件頂端"],
  cursorTopSelect: ["Select to document top", "選取至文件頂端"],
  cursorUndo: ["Cursor Undo", "復原游標移動"],
  cursorUp: ["Move cursor to previous line", "將游標移至上一行"],
  cursorUpSelect: ["Select to previous line", "選取至上一行"],
  cursorWordAccessibilityLeft: [
    "Move cursor to previous word (accessible)",
    "將游標移至左側單字（無障礙）",
  ],
  cursorWordAccessibilityLeftSelect: [
    "Select to previous word (accessible)",
    "選取至左側單字（無障礙）",
  ],
  cursorWordAccessibilityRight: [
    "Move cursor to next word (accessible)",
    "將游標移至右側單字（無障礙）",
  ],
  cursorWordAccessibilityRightSelect: [
    "Select to next word (accessible)",
    "選取至右側單字（無障礙）",
  ],
  cursorWordEndLeft: ["Move cursor to previous word end", "將游標移至左側單字結尾"],
  cursorWordEndLeftSelect: ["Select to previous word end", "選取至左側單字結尾"],
  cursorWordEndRight: ["Move cursor to next word end", "將游標移至右側單字結尾"],
  cursorWordEndRightSelect: ["Select to next word end", "選取至右側單字結尾"],
  cursorWordLeft: ["Move cursor to previous word", "將游標移至左側單字"],
  cursorWordLeftSelect: ["Select to previous word", "選取至左側單字"],
  cursorWordPartLeft: ["Move cursor to previous word part", "將游標移至左側單字片段"],
  cursorWordPartLeftSelect: ["Select to previous word part", "選取至左側單字片段"],
  cursorWordPartRight: ["Move cursor to next word part", "將游標移至右側單字片段"],
  cursorWordPartRightSelect: ["Select to next word part", "選取至右側單字片段"],
  cursorWordRight: ["Move cursor to next word", "將游標移至右側單字"],
  cursorWordRightSelect: ["Select to next word", "選取至右側單字"],
  cursorWordStartLeft: ["Move cursor to previous word start", "將游標移至左側單字開頭"],
  cursorWordStartLeftSelect: ["Select to previous word start", "選取至左側單字開頭"],
  cursorWordStartRight: ["Move cursor to next word start", "將游標移至右側單字開頭"],
  cursorWordStartRightSelect: ["Select to next word start", "選取至右側單字開頭"],
  deleteAllLeft: ["Delete All Left", "刪除至行首"],
  deleteAllRight: ["Delete All Right", "刪除至行尾"],
  deleteInsideWord: ["Delete Word", "刪除目前單字"],
  deleteLeft: ["Delete character to the left", "刪除左側字元"],
  deleteRight: ["Delete character to the right", "刪除右側字元"],
  deleteWordEndLeft: ["Delete to previous word end", "刪除至左側單字結尾"],
  deleteWordEndRight: ["Delete to next word end", "刪除至右側單字結尾"],
  deleteWordLeft: ["Delete to previous word", "刪除至左側單字"],
  deleteWordPartLeft: ["Delete to previous word part", "刪除至左側單字片段"],
  deleteWordPartRight: ["Delete to next word part", "刪除至右側單字片段"],
  deleteWordRight: ["Delete to next word", "刪除至右側單字"],
  deleteWordStartLeft: ["Delete to previous word start", "刪除至左側單字開頭"],
  deleteWordStartRight: ["Delete to next word start", "刪除至右側單字開頭"],
  "diffEditor.exitCompareMove": ["Exit moved code comparison", "離開移動區塊比較"],
  "editor.action.accessibleDiffViewer.next": [
    "Accessible diff viewer: next difference",
    "無障礙差異檢視：下一個差異",
  ],
  "editor.action.accessibleDiffViewer.prev": [
    "Accessible diff viewer: previous difference",
    "無障礙差異檢視：上一個差異",
  ],
  "editor.action.addCommentLine": ["Add Line Comment", "加入行註解"],
  "editor.action.addCursorsToBottom": ["Add Cursors To Bottom", "新增游標至文件底部"],
  "editor.action.addCursorsToTop": ["Add Cursors To Top", "新增游標至文件頂端"],
  "editor.action.addSelectionToNextFindMatch": ["Add next occurrence", "選取下一個相同文字"],
  "editor.action.addSelectionToPreviousFindMatch": [
    "Add Selection To Previous Find Match",
    "選取上一個相同文字",
  ],
  "editor.action.autoFix": ["Auto Fix...", "自動修正"],
  "editor.action.blockComment": ["Toggle block comment", "切換區塊註解"],
  "editor.action.cancelSelectionAnchor": ["Cancel Selection Anchor", "取消選取錨點"],
  "editor.action.changeAll": ["Change All Occurrences", "變更所有相同文字"],
  "editor.action.changeTabDisplaySize": ["Change Tab Display Size", "變更定位字元顯示寬度"],
  "editor.action.clipboardCopyAction": ["Copy", "複製"],
  "editor.action.clipboardCopyWithSyntaxHighlightingAction": [
    "Copy With Syntax Highlighting",
    "複製並保留語法色彩",
  ],
  "editor.action.clipboardCutAction": ["Cut", "剪下"],
  "editor.action.clipboardPasteAction": ["Paste", "貼上"],
  "editor.action.codeAction": ["Show code actions", "顯示程式碼動作"],
  "editor.action.commentLine": ["Toggle line comment", "切換行註解"],
  "editor.action.copyLinesDownAction": ["Copy Line Down", "向下複製行"],
  "editor.action.copyLinesUpAction": ["Copy Line Up", "向上複製行"],
  "editor.action.decreaseHoverVerbosityLevel": [
    "Decrease Hover Verbosity Level",
    "減少懸停提示的詳細內容",
  ],
  "editor.action.deleteLines": ["Delete Line", "刪除行"],
  "editor.action.detectIndentation": ["Detect Indentation from Content", "從內容偵測縮排"],
  "editor.action.duplicateSelection": ["Duplicate Selection", "複製選取內容"],
  "editor.action.fixAll": ["Fix All", "修正所有問題"],
  "editor.action.focusNextCursor": ["Focus Next Cursor", "將焦點移至下一個游標"],
  "editor.action.focusPreviousCursor": ["Focus Previous Cursor", "將焦點移至上一個游標"],
  "editor.action.fontZoomIn": ["Increase Editor Font Size", "放大編輯器字級"],
  "editor.action.fontZoomOut": ["Decrease Editor Font Size", "縮小編輯器字級"],
  "editor.action.fontZoomReset": ["Reset Editor Font Size", "還原編輯器字級"],
  "editor.action.forceRetokenize": ["Developer: Force Retokenize", "開發者：重新分析語法標記"],
  "editor.action.formatSelection": ["Format Selection", "格式化選取範圍"],
  "editor.action.goToBottomHover": ["Go To Bottom Hover", "前往懸停提示底部"],
  "editor.action.goToFocusedStickyScrollLine": [
    "Go to focused sticky scroll line",
    "前往目前聚焦的固定行",
  ],
  "editor.action.goToImplementation": ["Go to implementation", "前往實作"],
  "editor.action.goToMatchFindAction": ["Go to Match...", "前往指定相符項目"],
  "editor.action.goToReferences": ["Go to references", "前往參考"],
  "editor.action.goToSelectionAnchor": ["Go to Selection Anchor", "前往選取錨點"],
  "editor.action.goToTopHover": ["Go To Top Hover", "前往懸停提示頂端"],
  "editor.action.gotoLine": ["Go to Line/Column...", "前往行／欄"],
  "editor.action.hideColorPicker": ["Hide the Color Picker", "隱藏色彩選擇器"],
  "editor.action.inPlaceReplace.down": ["Replace with Next Value", "取代為下一個值"],
  "editor.action.inPlaceReplace.up": ["Replace with Previous Value", "取代為上一個值"],
  "editor.action.increaseHoverVerbosityLevel": [
    "Increase Hover Verbosity Level",
    "增加懸停提示的詳細內容",
  ],
  "editor.action.indentLines": ["Indent Line", "增加行縮排"],
  "editor.action.indentUsingSpaces": ["Indent Using Spaces", "使用空格縮排"],
  "editor.action.indentUsingTabs": ["Indent Using Tabs", "使用定位字元縮排"],
  "editor.action.indentationToSpaces": ["Convert Indentation to Spaces", "將縮排轉換為空格"],
  "editor.action.indentationToTabs": ["Convert Indentation to Tabs", "將縮排轉換為定位字元"],
  "editor.action.inlineEdit.accept": ["Accept Inline Edit", "接受行內編輯"],
  "editor.action.inlineEdit.jumpBack": ["Jump Back from Inline Edit", "從行內編輯返回"],
  "editor.action.inlineEdit.jumpTo": ["Jump to Inline Edit", "前往行內編輯"],
  "editor.action.inlineEdit.reject": ["Reject Inline Edit", "拒絕行內編輯"],
  "editor.action.inlineEdit.trigger": ["Trigger Inline Edit", "觸發行內編輯"],
  "editor.action.inlineEdits.accept": ["Accept Inline Edit", "接受行內編輯建議"],
  "editor.action.inlineEdits.hide": ["Hide Inline Edit", "隱藏行內編輯"],
  "editor.action.inlineEdits.showNext": ["Show Next Inline Edit", "顯示下一個行內編輯"],
  "editor.action.inlineEdits.showPrevious": ["Show Previous Inline Edit", "顯示上一個行內編輯"],
  "editor.action.inlineEdits.trigger": ["Trigger Inline Edit", "觸發行內編輯建議"],
  "editor.action.inlineSuggest.acceptNextLine": [
    "Accept Next Line Of Inline Suggestion",
    "接受行內建議的下一行",
  ],
  "editor.action.inlineSuggest.acceptNextWord": [
    "Accept Next Word Of Inline Suggestion",
    "接受行內建議的下一個單字",
  ],
  "editor.action.inlineSuggest.commit": ["Accept Inline Suggestion", "接受行內建議"],
  "editor.action.inlineSuggest.hide": ["Hide Inline Suggestion", "隱藏行內建議"],
  "editor.action.inlineSuggest.showNext": ["Show Next Inline Suggestion", "顯示下一個行內建議"],
  "editor.action.inlineSuggest.showPrevious": [
    "Show Previous Inline Suggestion",
    "顯示上一個行內建議",
  ],
  "editor.action.inlineSuggest.trigger": ["Trigger Inline Suggestion", "觸發行內建議"],
  "editor.action.insertColorWithStandaloneColorPicker": [
    "Insert Color with Standalone Color Picker",
    "使用獨立色彩選擇器插入色彩",
  ],
  "editor.action.insertCursorAbove": ["Add cursor above", "在上方新增游標"],
  "editor.action.insertCursorAtEndOfEachLineSelected": [
    "Add Cursors to Line Ends",
    "在選取的每行結尾新增游標",
  ],
  "editor.action.insertCursorBelow": ["Add cursor below", "在下方新增游標"],
  "editor.action.insertLineAfter": ["Insert Line Below", "在下方插入行"],
  "editor.action.insertLineBefore": ["Insert Line Above", "在上方插入行"],
  "editor.action.inspectTokens": ["Developer: Inspect Tokens", "開發者：檢查語法標記"],
  "editor.action.joinLines": ["Join Lines", "合併行"],
  "editor.action.jumpToBracket": ["Go to Bracket", "前往對應括號"],
  "editor.action.linkedEditing": ["Start Linked Editing", "開始連動編輯"],
  "editor.action.marker.next": ["Go to Next Problem (Error, Warning, Info)", "檔案中的下一個診斷"],
  "editor.action.marker.prev": [
    "Go to Previous Problem (Error, Warning, Info)",
    "檔案中的上一個診斷",
  ],
  "editor.action.moveCarretLeftAction": ["Move Selected Text Left", "向左移動選取文字"],
  "editor.action.moveCarretRightAction": ["Move Selected Text Right", "向右移動選取文字"],
  "editor.action.moveLinesDownAction": ["Move Line Down", "向下移動行"],
  "editor.action.moveLinesUpAction": ["Move Line Up", "向上移動行"],
  "editor.action.moveSelectionToNextFindMatch": [
    "Move Last Selection To Next Find Match",
    "將最後的選取範圍移至下一個相符項目",
  ],
  "editor.action.moveSelectionToPreviousFindMatch": [
    "Move Last Selection To Previous Find Match",
    "將最後的選取範圍移至上一個相符項目",
  ],
  "editor.action.nextMatchFindAction": ["Find Next", "搜尋下一個相符項目"],
  "editor.action.nextSelectionMatchFindAction": [
    "Find Next Selection",
    "搜尋下一個與選取文字相符的項目",
  ],
  "editor.action.openLink": ["Open Link", "開啟連結"],
  "editor.action.organizeImports": ["Organize Imports", "整理匯入"],
  "editor.action.outdentLines": ["Outdent Line", "減少行縮排"],
  "editor.action.pageDownHover": ["Page Down Hover", "將懸停提示向下捲動一頁"],
  "editor.action.pageUpHover": ["Page Up Hover", "將懸停提示向上捲動一頁"],
  "editor.action.pasteAs": ["Paste As...", "選擇貼上方式"],
  "editor.action.pasteAsText": ["Paste as Text", "貼上為純文字"],
  "editor.action.peekDefinition": ["Peek definition", "預覽定義"],
  "editor.action.peekImplementation": ["Peek implementation", "預覽實作"],
  "editor.action.previousMatchFindAction": ["Find Previous", "搜尋上一個相符項目"],
  "editor.action.previousSelectionMatchFindAction": [
    "Find Previous Selection",
    "搜尋上一個與選取文字相符的項目",
  ],
  "editor.action.quickCommand": ["Command palette", "命令選單"],
  "editor.action.quickFix": ["Quick Fix...", "快速修正"],
  "editor.action.quickOutline": ["Go to Symbol...", "前往符號"],
  "editor.action.refactor": ["Refactor...", "重構"],
  "editor.action.reindentlines": ["Reindent Lines", "重新縮排所有行"],
  "editor.action.reindentselectedlines": ["Reindent Selected Lines", "重新縮排選取的行"],
  "editor.action.removeBrackets": ["Remove Brackets", "移除括號"],
  "editor.action.removeCommentLine": ["Remove Line Comment", "移除行註解"],
  "editor.action.removeDuplicateLines": ["Delete Duplicate Lines", "刪除重複行"],
  "editor.action.rename": ["Rename Symbol", "重新命名符號"],
  "editor.action.replaceAll": ["Replace all", "全部取代"],
  "editor.action.replaceOne": ["Replace current match", "取代目前相符項目"],
  "editor.action.resetSuggestSize": ["Reset Suggest Widget Size", "還原建議清單大小"],
  "editor.action.revealDefinition": ["Go to definition", "前往定義"],
  "editor.action.revealDefinitionAside": ["Open definition to the side", "在側邊開啟定義"],
  "editor.action.scrollDownHover": ["Scroll Down Hover", "向下捲動懸停提示"],
  "editor.action.scrollLeftHover": ["Scroll Left Hover", "向左捲動懸停提示"],
  "editor.action.scrollRightHover": ["Scroll Right Hover", "向右捲動懸停提示"],
  "editor.action.scrollUpHover": ["Scroll Up Hover", "向上捲動懸停提示"],
  "editor.action.selectAll": ["Select all", "全選"],
  "editor.action.selectAllMatches": ["Select all search matches", "選取所有搜尋結果"],
  "editor.action.selectEditor": ["Focus editor", "將焦點移至編輯器"],
  "editor.action.selectFromAnchorToCursor": ["Select from Anchor to Cursor", "從錨點選取至游標"],
  "editor.action.selectHighlights": ["Select all occurrences", "選取所有相同文字"],
  "editor.action.selectNextStickyScrollLine": [
    "Select next sticky scroll line",
    "選取下一個固定行",
  ],
  "editor.action.selectPreviousStickyScrollLine": [
    "Select previous sticky scroll line",
    "選取上一個固定行",
  ],
  "editor.action.selectToBracket": ["Select to Bracket", "選取至對應括號"],
  "editor.action.setSelectionAnchor": ["Set Selection Anchor", "設定選取錨點"],
  "editor.action.showContextMenu": ["Show Editor Context Menu", "顯示編輯器快顯選單"],
  "editor.action.showDefinitionPreviewHover": ["Show Definition Preview Hover", "顯示定義預覽提示"],
  "editor.action.showHover": ["Show or Focus Hover", "顯示或聚焦懸停提示"],
  "editor.action.smartSelect.expand": ["Expand Selection", "擴大選取範圍"],
  "editor.action.smartSelect.shrink": ["Shrink Selection", "縮小選取範圍"],
  "editor.action.sortLinesAscending": ["Sort Lines Ascending", "依遞增順序排列行"],
  "editor.action.sortLinesDescending": ["Sort Lines Descending", "依遞減順序排列行"],
  "editor.action.sourceAction": ["Source Action...", "原始碼動作"],
  "editor.action.startFindReplaceAction": ["Replace", "取代"],
  "editor.action.toggleHighContrast": ["Toggle High Contrast Theme", "切換高對比主題"],
  "editor.action.toggleTabFocusMode": ["Toggle Tab focus mode", "切換 Tab 焦點移動模式"],
  "editor.action.transformToCamelcase": ["Transform to Camel Case", "轉換為小駝峰命名"],
  "editor.action.transformToKebabcase": ["Transform to Kebab Case", "轉換為連字號命名"],
  "editor.action.transformToLowercase": ["Transform to Lowercase", "轉換為小寫"],
  "editor.action.transformToPascalcase": ["Transform to Pascal Case", "轉換為大駝峰命名"],
  "editor.action.transformToSnakecase": ["Transform to Snake Case", "轉換為底線命名"],
  "editor.action.transformToTitlecase": ["Transform to Title Case", "轉換為每字字首大寫"],
  "editor.action.transformToUppercase": ["Transform to Uppercase", "轉換為大寫"],
  "editor.action.transpose": ["Transpose Characters around the Cursor", "交換游標兩側字元"],
  "editor.action.transposeLetters": ["Transpose Letters", "交換字母"],
  "editor.action.triggerParameterHints": ["Trigger Parameter Hints", "觸發參數提示"],
  "editor.action.triggerSuggest": ["Trigger Suggest", "觸發補全建議"],
  "editor.action.trimTrailingWhitespace": ["Trim Trailing Whitespace", "移除行尾空白"],
  "editor.action.unicodeHighlight.disableHighlightingOfAmbiguousCharacters": [
    "Disable highlighting of ambiguous characters",
    "停用易混淆字元醒目提示",
  ],
  "editor.action.unicodeHighlight.disableHighlightingOfInvisibleCharacters": [
    "Disable highlighting of invisible characters",
    "停用不可見字元醒目提示",
  ],
  "editor.action.unicodeHighlight.disableHighlightingOfNonBasicAsciiCharacters": [
    "Disable highlighting of non basic ASCII characters",
    "停用非基本 ASCII 字元醒目提示",
  ],
  "editor.action.unicodeHighlight.showExcludeOptions": [
    "Show Exclude Options",
    "顯示字元醒目提示排除選項",
  ],
  "editor.action.wordHighlight.next": ["Go to Next Symbol Highlight", "前往下一個醒目提示符號"],
  "editor.action.wordHighlight.prev": ["Go to Previous Symbol Highlight", "前往上一個醒目提示符號"],
  "editor.action.wordHighlight.trigger": ["Trigger Symbol Highlight", "觸發符號醒目提示"],
  "editor.actions.findWithArgs": ["Find With Arguments", "使用指定參數搜尋"],
  "editor.cancelOperation": ["Cancel editor operation", "取消編輯器操作"],
  "editor.changeDropType": ["Change drop type", "變更拖放方式"],
  "editor.changePasteType": ["Change paste type", "變更貼上方式"],
  "editor.createFoldingRangeFromSelection": [
    "Create Folding Range from Selection",
    "從選取範圍建立摺疊區域",
  ],
  "editor.fold": ["Fold", "摺疊"],
  "editor.foldAll": ["Fold All", "全部摺疊"],
  "editor.foldAllBlockComments": ["Fold All Block Comments", "摺疊所有區塊註解"],
  "editor.foldAllExcept": ["Fold All Except Selected", "摺疊選取範圍以外的所有區域"],
  "editor.foldAllMarkerRegions": ["Fold All Regions", "摺疊所有標記區域"],
  "editor.foldLevel1": ["Fold level 1", "摺疊第 1 層"],
  "editor.foldLevel2": ["Fold level 2", "摺疊第 2 層"],
  "editor.foldLevel3": ["Fold level 3", "摺疊第 3 層"],
  "editor.foldLevel4": ["Fold level 4", "摺疊第 4 層"],
  "editor.foldLevel5": ["Fold level 5", "摺疊第 5 層"],
  "editor.foldLevel6": ["Fold level 6", "摺疊第 6 層"],
  "editor.foldLevel7": ["Fold level 7", "摺疊第 7 層"],
  "editor.foldRecursively": ["Fold Recursively", "遞迴摺疊"],
  "editor.gotoNextFold": ["Go to Next Folding Range", "前往下一個摺疊區域"],
  "editor.gotoNextSymbolFromResult": ["Go to next symbol in results", "前往結果中的下一個符號"],
  "editor.gotoNextSymbolFromResult.cancel": [
    "Cancel symbol result navigation",
    "取消結果中的符號導覽",
  ],
  "editor.gotoParentFold": ["Go to Parent Fold", "前往上層摺疊區域"],
  "editor.gotoPreviousFold": ["Go to Previous Folding Range", "前往上一個摺疊區域"],
  "editor.hideDropWidget": ["Hide drop options", "隱藏拖放選項"],
  "editor.hidePasteWidget": ["Hide paste options", "隱藏貼上選項"],
  "editor.removeManualFoldingRanges": ["Remove Manual Folding Ranges", "移除手動摺疊區域"],
  "editor.toggleFold": ["Toggle Fold", "切換摺疊"],
  "editor.toggleFoldRecursively": ["Toggle Fold Recursively", "遞迴切換摺疊"],
  "editor.unfold": ["Unfold", "展開"],
  "editor.unfoldAll": ["Unfold All", "全部展開"],
  "editor.unfoldAllExcept": ["Unfold All Except Selected", "展開選取範圍以外的所有區域"],
  "editor.unfoldAllMarkerRegions": ["Unfold All Regions", "展開所有標記區域"],
  "editor.unfoldRecursively": ["Unfold Recursively", "遞迴展開"],
  editorScroll: ["Scroll editor with options", "依指定方式捲動編輯器"],
  expandLineSelection: ["Expand Line Selection", "擴大整行選取範圍"],
  focusAndAcceptSuggestion: ["Focus and accept suggestion", "聚焦並接受建議"],
  focusNextRenameSuggestion: ["Focus next rename suggestion", "聚焦下一個重新命名建議"],
  focusPreviousRenameSuggestion: ["Focus previous rename suggestion", "聚焦上一個重新命名建議"],
  focusSuggestion: ["Focus suggestion list", "將焦點移至建議清單"],
  goToNextReference: ["Go to next reference", "前往下一個參考"],
  goToPreviousReference: ["Go to previous reference", "前往上一個參考"],
  hideCodeActionWidget: ["Hide code action menu", "隱藏程式碼動作選單"],
  hideSuggestWidget: ["Hide suggestion list", "隱藏建議清單"],
  "history.showNext": ["Show next input history entry", "顯示下一筆輸入紀錄"],
  "history.showPrevious": ["Show previous input history entry", "顯示上一筆輸入紀錄"],
  insertBestCompletion: ["Insert best completion", "插入最佳補全項目"],
  insertNextSuggestion: ["Insert next suggestion", "插入下一個建議"],
  insertPrevSuggestion: ["Insert previous suggestion", "插入上一個建議"],
  jumpToNextSnippetPlaceholder: ["Go to next snippet placeholder", "前往下一個程式碼片段欄位"],
  jumpToPrevSnippetPlaceholder: ["Go to previous snippet placeholder", "前往上一個程式碼片段欄位"],
  "kobrixa.build": ["Build", "編譯"],
  "kobrixa.preview": ["Local simulator", "本地模擬器"],
  "kobrixa.closeTab": ["Close tab", "關閉分頁"],
  "kobrixa.device": ["Toggle EV3 tools", "切換 EV3 面板"],
  "kobrixa.files": ["Toggle file tree", "切換檔案樹"],
  "kobrixa.format": ["Format document", "格式化文件"],
  "kobrixa.newProject": ["New project", "新增專案"],
  "kobrixa.nextProblem": ["Next diagnostic", "下一個診斷"],
  "kobrixa.nextTab": ["Next tab", "下一個分頁"],
  "kobrixa.openProject": ["Open project", "開啟專案"],
  "kobrixa.previousProblem": ["Previous diagnostic", "上一個診斷"],
  "kobrixa.previousTab": ["Previous tab", "上一個分頁"],
  "kobrixa.problems": ["Toggle diagnostics", "切換診斷面板"],
  "kobrixa.quickOpen": ["Quick open file", "快速開檔"],
  "kobrixa.run": ["Run on EV3", "在 EV3 執行"],
  "kobrixa.save": ["Save", "儲存"],
  "kobrixa.saveAll": ["Save all", "全部儲存"],
  "kobrixa.search": ["Search project files", "跨檔案搜尋"],
  "kobrixa.settings": ["Settings", "設定"],
  "kobrixa.shortcuts": ["Keyboard shortcuts", "快捷鍵"],
  "kobrixa.stop": ["Stop / cancel build", "停止／取消編譯"],
  lastCursorLineSelect: ["Select line with last cursor", "以最後一個游標選取整行"],
  lastCursorLineSelectDrag: ["Drag to select lines with last cursor", "以最後一個游標拖曳選取整行"],
  lastCursorWordSelect: ["Select word with last cursor", "以最後一個游標選取單字"],
  leaveEditorMessage: ["Dismiss editor message", "關閉編輯器訊息"],
  leaveSnippet: ["Leave snippet mode", "離開程式碼片段模式"],
  lineBreakInsert: ["Insert line break", "插入換行"],
  openReferenceToSide: ["Open reference to the side", "在側邊開啟參考"],
  outdent: ["Decrease indentation at cursor", "減少游標處縮排"],
  previewSelectedCodeAction: ["Preview selected code action", "預覽選取的程式碼動作"],
  "quickInput.acceptInBackground": [
    "Accept quick pick item in background",
    "在背景接受快速選單項目",
  ],
  "quickInput.first": ["Quick pick: first item", "快速選單：第一個項目"],
  "quickInput.last": ["Quick pick: last item", "快速選單：最後一個項目"],
  "quickInput.next": ["Quick pick: next item", "快速選單：下一個項目"],
  "quickInput.nextSeparator": ["Quick pick: next group", "快速選單：下一個群組"],
  "quickInput.nextSeparatorWithQuickAccessFallback": [
    "Quick pick: next group or item",
    "快速選單：下一個群組或項目",
  ],
  "quickInput.pageNext": ["Quick pick: next page", "快速選單：下一頁"],
  "quickInput.pagePrevious": ["Quick pick: previous page", "快速選單：上一頁"],
  "quickInput.previous": ["Quick pick: previous item", "快速選單：上一個項目"],
  "quickInput.previousSeparator": ["Quick pick: previous group", "快速選單：上一個群組"],
  "quickInput.previousSeparatorWithQuickAccessFallback": [
    "Quick pick: previous group or item",
    "快速選單：上一個群組或項目",
  ],
  redo: ["Redo", "重做"],
  removeSecondaryCursors: ["Remove secondary cursors", "移除其他游標"],
  revealLine: ["Reveal line", "顯示指定行"],
  revealReference: ["Reveal reference", "顯示參考"],
  scrollEditorBottom: ["Scroll to document bottom", "捲動至文件底部"],
  scrollEditorTop: ["Scroll to document top", "捲動至文件頂端"],
  scrollLeft: ["Scroll left", "向左捲動"],
  scrollLineDown: ["Scroll down one line", "向下捲動一行"],
  scrollLineUp: ["Scroll up one line", "向上捲動一行"],
  scrollPageDown: ["Scroll down one page", "向下捲動一頁"],
  scrollPageUp: ["Scroll up one page", "向上捲動一頁"],
  scrollRight: ["Scroll right", "向右捲動"],
  selectFirstSuggestion: ["Select first suggestion", "選取第一個建議"],
  selectLastSuggestion: ["Select last suggestion", "選取最後一個建議"],
  selectNextCodeAction: ["Select next code action", "選取下一個程式碼動作"],
  selectNextPageSuggestion: ["Select next page of suggestions", "選取下一頁建議"],
  selectNextSuggestion: ["Select next suggestion", "選取下一個建議"],
  selectPrevCodeAction: ["Select previous code action", "選取上一個程式碼動作"],
  selectPrevPageSuggestion: ["Select previous page of suggestions", "選取上一頁建議"],
  selectPrevSuggestion: ["Select previous suggestion", "選取上一個建議"],
  setSelection: ["Set selection", "設定選取範圍"],
  showNextParameterHint: ["Show next parameter hint", "顯示下一個參數提示"],
  showPrevParameterHint: ["Show previous parameter hint", "顯示上一個參數提示"],
  tab: ["Insert tab or indent", "插入定位字元或縮排"],
  toggleExplainMode: ["Toggle suggestion explanation mode", "切換建議解說模式"],
  toggleFindCaseSensitive: ["Toggle case-sensitive search", "切換搜尋區分大小寫"],
  toggleFindInSelection: ["Toggle find in selection", "切換在選取範圍內搜尋"],
  toggleFindRegex: ["Toggle regular expression search", "切換規則運算式搜尋"],
  toggleFindWholeWord: ["Toggle whole-word search", "切換全字相符搜尋"],
  togglePeekWidgetFocus: ["Toggle peek widget focus", "切換預覽視窗焦點"],
  togglePreserveCase: ["Toggle preserve case when replacing", "切換取代時保留大小寫"],
  toggleSuggestionDetails: ["Toggle suggestion details", "切換建議詳細資訊"],
  toggleSuggestionFocus: ["Toggle suggestion focus", "切換建議清單焦點"],
  undo: ["Undo", "復原"],
};
