import { z } from "zod";
import { COLLAB_LIMITS } from "./constants.js";

export const roleSchema = z.enum(["host", "editor", "viewer"]);
export type Role = z.infer<typeof roleSchema>;

/** Room ids are opaque, URL-safe and generated by the server. */
export const roomIdSchema = z.string().regex(/^[A-Za-z0-9_-]{16,64}$/);
/** Participant ids are stable for one join and reused across reconnects. */
export const participantIdSchema = z.string().regex(/^[A-Za-z0-9_-]{8,64}$/);
/** Human-shareable invite code, e.g. `ABCD-EFGH-JKLM`. */
export const inviteCodeSchema = z.string().regex(/^[A-HJ-NP-Z2-9]{4}(-[A-HJ-NP-Z2-9]{4}){2}$/);
export const displayNameSchema = z
  .string()
  .trim()
  .min(1)
  .max(COLLAB_LIMITS.displayNameLength)
  .refine(
    // Rejects C0/C1 controls and bidi/format characters that could spoof other names.
    (name) => !/[\p{Cc}\p{Cf}]/u.test(name),
    "control characters",
  );
/** Workspace-relative POSIX path, as used by the desktop workspace service. */
export const collabPathSchema = z
  .string()
  .min(1)
  .max(1024)
  .refine(
    (path) =>
      !path.startsWith("/") &&
      !path.includes("\0") &&
      !path.includes("\\") &&
      path.split("/").every((part) => part !== "" && part !== "." && part !== ".."),
    "relative path",
  );

/** Passwords are case-sensitive; preserve whitespace exactly. Empty means no password. */
export const roomPasswordSchema = z.string().max(COLLAB_LIMITS.roomPasswordLength);

export const createRoomRequestSchema = z
  .object({
    name: displayNameSchema,
    projectName: z.string().trim().min(1).max(120),
    password: roomPasswordSchema.optional(),
  })
  .strict();
export type CreateRoomRequest = z.infer<typeof createRoomRequestSchema>;

export const createRoomResponseSchema = z
  .object({
    roomId: roomIdSchema,
    inviteCode: inviteCodeSchema,
    participantId: participantIdSchema,
    hostToken: z.string().min(1),
    expiresAt: z.number().int(),
  })
  .strict();
export type CreateRoomResponse = z.infer<typeof createRoomResponseSchema>;

export const joinRequestSchema = z
  .object({
    inviteCode: inviteCodeSchema,
    name: displayNameSchema,
    password: roomPasswordSchema.optional(),
  })
  .strict();
export type JoinRequest = z.infer<typeof joinRequestSchema>;

export const joinResponseSchema = z
  .object({
    roomId: roomIdSchema,
    participantId: participantIdSchema,
    token: z.string().min(1),
    role: roleSchema,
    projectName: z.string(),
    expiresAt: z.number().int(),
  })
  .strict();
export type JoinResponse = z.infer<typeof joinResponseSchema>;

export const resumeCredentialSchema = z.string().regex(/^[A-Za-z0-9_-]{43}$/);
export const resumableCreateResponseSchema = createRoomResponseSchema.extend({
  resumeCredential: resumeCredentialSchema.optional(),
});
export const resumableJoinResponseSchema = joinResponseSchema.extend({
  resumeCredential: resumeCredentialSchema.optional(),
});
export const resumeRequestSchema = z
  .object({
    participantId: participantIdSchema,
    credential: resumeCredentialSchema,
  })
  .strict();
export const resumeResponseSchema = joinResponseSchema.extend({
  name: displayNameSchema,
  inviteCode: inviteCodeSchema,
});

/** Host-only. Disconnects a participant and revokes its token. */
export const kickRequestSchema = z.object({ participantId: participantIdSchema }).strict();
export type KickRequest = z.infer<typeof kickRequestSchema>;

/** Host-only. Changes the role of a connected or previously joined participant. */
export const setRoleRequestSchema = z
  .object({ participantId: participantIdSchema, role: z.enum(["editor", "viewer"]) })
  .strict();
export type SetRoleRequest = z.infer<typeof setRoleRequestSchema>;

/** Signed by the server (HMAC-SHA256); clients treat tokens as opaque strings. */
export const tokenPayloadSchema = z
  .object({
    v: z.literal(1),
    roomId: roomIdSchema,
    participantId: participantIdSchema,
    role: roleSchema,
    name: displayNameSchema,
    exp: z.number().int(),
  })
  .strict();
export type TokenPayload = z.infer<typeof tokenPayloadSchema>;

export const errorResponseSchema = z
  .object({
    error: z.enum([
      "bad-request",
      "unauthorized",
      "password-required",
      "invalid-password",
      "forbidden",
      "not-found",
      "room-full",
      "rate-limited",
      "expired",
      "internal",
      "room-closed",
      "removed",
    ]),
    message: z.string().optional(),
  })
  .strict();
export type ErrorResponse = z.infer<typeof errorResponseSchema>;

export const selectionSchema = z
  .object({
    anchor: z.number().int().nonnegative(),
    head: z.number().int().nonnegative(),
  })
  .strict();
export type CollabSelection = z.infer<typeof selectionSchema>;

/**
 * Awareness state published by every client (y-protocols awareness).
 * `anchor`/`head` are Y.RelativePosition JSON when available, otherwise
 * absolute offsets into the file's Y.Text.
 */
export const presenceStateSchema = z
  .object({
    participantId: participantIdSchema,
    name: displayNameSchema,
    color: z.string().regex(/^#[0-9a-f]{6}$/i),
    role: roleSchema,
    file: collabPathSchema.optional(),
    selection: z.object({ anchor: z.unknown(), head: z.unknown() }).strict().optional(),
  })
  .strict();
export type PresenceState = z.infer<typeof presenceStateSchema>;

export const chatMessageSchema = z
  .object({
    id: z.string().min(1).max(64),
    participantId: participantIdSchema,
    name: displayNameSchema,
    text: z.string().trim().min(1).max(COLLAB_LIMITS.chatMessageLength),
    at: z.number().int(),
  })
  .strict();
export type ChatMessage = z.infer<typeof chatMessageSchema>;

export const sendChatRequestSchema = chatMessageSchema.pick({ id: true, text: true });
export type SendChatRequest = z.infer<typeof sendChatRequestSchema>;

export const treeEntrySchema = z.object({ kind: z.enum(["file", "directory"]) }).strict();
export type TreeEntry = z.infer<typeof treeEntrySchema>;

/** Values stored under the `control` Y.Map. */
export const controlStateSchema = z
  .object({
    /** Participant allowed to upload/run on an EV3. Defaults to the host. */
    holder: participantIdSchema.nullable(),
    /** Pending requests for device control, in request order. */
    requests: z.array(participantIdSchema).max(COLLAB_LIMITS.participants),
  })
  .strict();
export type ControlState = z.infer<typeof controlStateSchema>;

/**
 * JSON payload of a `MESSAGE_TYPE.control` WebSocket frame (client → server).
 * `decline` (host only) removes a pending device-control request and sends the
 * requester a `control-declined` notice. Servers ignore unknown commands.
 */
export const controlCommandSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("decline"), participantId: participantIdSchema }).strict(),
]);
export type ControlCommand = z.infer<typeof controlCommandSchema>;

/** JSON payload of a `MESSAGE_TYPE.notice` WebSocket frame (server → client). */
export const noticeSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("kicked") }).strict(),
  z.object({ type: z.literal("role"), role: roleSchema }).strict(),
  z.object({ type: z.literal("room-closed") }).strict(),
  /** The host declined this participant's device-control request (older clients ignore it). */
  z.object({ type: z.literal("control-declined") }).strict(),
  z
    .object({
      type: z.literal("participants"),
      participants: z.array(
        z
          .object({
            participantId: participantIdSchema,
            name: displayNameSchema,
            role: roleSchema,
            online: z.boolean(),
          })
          .strict(),
      ),
    })
    .strict(),
]);
export type Notice = z.infer<typeof noticeSchema>;
