export const previewCopy = {
  en: {
    title: "Offline preview",
    close: "Close preview",
    run: "Run",
    pause: "Pause",
    step: "Step",
    stop: "Stop",
    reset: "Reset",
    rebuild: "Rebuild preview",
    speed: "Speed",
    loading: "Preparing preview…",
    ready: "Ready",
    running: "Running",
    paused: "Paused",
    completed: "Completed",
    stopped: "Stopped",
    error: "Preview stopped with an error",
    lcd: "Virtual EV3 display",
    virtual: "VIRTUAL EV3",
    inputs: "Sensor inputs",
    motors: "Motor outputs",
    events: "Output events",
    shortenedVariables: "Variable preview shortened to keep the simulator responsive.",
    variables: "Global variables",
    locals: "Local variables",
    location: "Program location",
    source: "Show source",
    elapsed: "Virtual time",
    instructions: "Instructions",
    threads: "Threads",
    empty: "None yet",
    port: "Port",
    type: "Type",
    mode: "Mode",
    percent: "Percent",
    raw: "Raw values",
    si: "SI values",
    busy: "Busy",
    battery: "Battery",
    up: "Up",
    down: "Down",
    left: "Left",
    right: "Right",
    enter: "Enter",
    back: "Back",
    buttons: "Virtual buttons",
    buttonsHint:
      "Hold a button, or focus this pad and use arrow keys / Enter / Backspace. Release to let go.",
    sensorHint:
      "Values are manual. Enter comma-separated values for multi-channel sensors; SI, raw and percent are independent. Program mode changes do not convert values.",
    valueError: "Enter 1–8 finite numbers separated by commas.",
    numberError: "Enter a finite number in the displayed range.",
    noSensor: "Disconnected",
    touch: "Touch",
    color: "Color",
    ultrasonic: "Ultrasonic",
    gyro: "Gyro",
    infrared: "Infrared",
    custom: "Custom",
    led: "LED",
    sound: "Sound",
    silent: "Idle",
    braking: "Brake",
    coasting: "Coast",
    disclosure:
      "This runs the compiled program locally without an EV3. Sensors are manual inputs; motor motion, sound timing and LCD fonts are approximations. It does not simulate physics or validate real wiring. Sound is shown in the event log, not played.",
    assets:
      "Unsupported operations or resource formats stop with an explanation. Local preview files are temporary and are cleared on reset. Rebuild after editing your code; Reset repeats this compiled version.",
    failed: "Could not start the preview worker.",
    files: "Virtual files",
    active: "Moving",
    idle: "Idle",
    count: "Position",
    power: "Speed",
    noLocation: "Run or step to inspect the program.",
    inspect: "Execution details",
    logHint: "Most recent 200 events",
    valuesHint: "Example: 42 or 10, 20, 30",
    stepHint: "Execute one program operation; waits advance virtual time.",
    runHint: "Run this compiled version",
    resetHint: "Reset time, output and variables; keep sensor settings",
    sensorType: "Sensor type number",
    sensorMode: "Sensor mode number",
  },
  "zh-TW": {
    title: "離線預演",
    close: "關閉預演",
    run: "執行",
    pause: "暫停",
    step: "單步",
    stop: "停止",
    reset: "重設",
    rebuild: "重新建置預演",
    speed: "速度",
    loading: "正在準備預演…",
    ready: "準備就緒",
    running: "執行中",
    paused: "已暫停",
    completed: "已完成",
    stopped: "已停止",
    error: "預演因錯誤停止",
    lcd: "虛擬 EV3 螢幕",
    virtual: "虛擬 EV3",
    inputs: "感測器輸入",
    motors: "馬達輸出",
    events: "輸出事件",
    shortenedVariables: "變數預覽已縮短，以保持介面流暢。",
    variables: "全域變數",
    locals: "區域變數",
    location: "程式位置",
    source: "查看原始碼",
    elapsed: "虛擬時間",
    instructions: "指令數",
    threads: "執行緒",
    empty: "尚無資料",
    port: "埠",
    type: "類型",
    mode: "模式",
    percent: "百分比",
    raw: "原始值",
    si: "SI 值",
    busy: "忙碌",
    battery: "電量",
    up: "上",
    down: "下",
    left: "左",
    right: "右",
    enter: "確認",
    back: "返回",
    buttons: "虛擬按鈕",
    buttonsHint: "按住按鈕，或將焦點移至按鈕區後使用方向鍵／Enter／Backspace；放開即解除。",
    sensorHint:
      "手動設定輸入。多通道以逗號分隔；SI、原始值及百分比各自獨立。程式切換模式時不會自動換算讀值。",
    valueError: "請輸入 1–8 個有限數字，以逗號分隔。",
    numberError: "請輸入範圍內的有限數字。",
    noSensor: "未連接",
    touch: "觸碰",
    color: "顏色",
    ultrasonic: "超音波",
    gyro: "陀螺儀",
    infrared: "紅外線",
    custom: "自訂",
    led: "指示燈",
    sound: "聲音",
    silent: "閒置",
    braking: "煞車",
    coasting: "滑行",
    disclosure:
      "直接在電腦上執行編譯後的程式，無需 EV3。感測器由手動輸入；馬達運動、聲音時間及 LCD 字型為近似值。不模擬物理環境或驗證實際接線。聲音以事件顯示，不播放音訊。",
    assets:
      "遇到不支援的操作或素材格式會停止並說明原因。預演檔案僅暫存於記憶體，重設後清除。修改程式後請重新建置；重設會重跑這份編譯版本。",
    failed: "無法啟動預演背景程序。",
    files: "虛擬檔案",
    active: "轉動中",
    idle: "閒置",
    count: "位置",
    power: "速度",
    noLocation: "執行或單步後即可查看程式位置。",
    inspect: "執行詳情",
    logHint: "最近 200 筆事件",
    valuesHint: "例如：42 或 10, 20, 30",
    stepHint: "執行一個程式操作；等待會推進虛擬時間。",
    runHint: "執行這份編譯版本",
    resetHint: "重設時間、輸出及變數；保留感測器設定",
    sensorType: "感測器類型編號",
    sensorMode: "感測器模式編號",
  },
} as const;
