import type { Role } from "@kobrixa/collab-protocol";
import type { Locale } from "../i18n/copy.js";
import type { CollabErrorCode } from "../../shared/collab.js";
import type { CollabCloseReason, CollabStatus } from "./types.js";
import type { ChatSendBlock } from "./chat.js";

export type DisplayNameProblem = "empty" | "too-long" | "invalid";

const en = {
  lobbyTitle: "Work together",
  lobbyIntro: "Share a project with classmates or teammates. Everyone edits the same files live.",
  displayName: "Your display name",
  displayNameHint: "Shown to everyone in the room.",
  displayNameProblems: {
    empty: "Enter a display name to start or join a room.",
    "too-long": "Use 40 characters or fewer.",
    invalid: "Remove control characters from the name.",
  } satisfies Record<DisplayNameProblem, string>,
  startRoom: "Start a room",
  startHint: (project: string) => `Invite others to edit “${project}”.`,
  startNeedsProject: "Open a project to start a room.",
  starting: "Starting room…",
  createIntro: "Project files will be shared with everyone who joins using your invite code.",
  roomPassword: "Room password (optional)",
  createPasswordHint: "Leave blank to allow joining with just the invite code.",
  joinPasswordHint: "If the host set a password, enter it here. It won't be remembered.",
  hostingAs: (name: string) => `You will host as ${name}.`,
  joinRoom: "Join a room",
  joinHint: "Have an invite code? Join someone else's project.",
  recentRooms: "Recent rooms",
  noRecentRooms: "Rooms you start or join appear here.",
  rejoin: "Rejoin",
  roles: { host: "Host", editor: "Editor", viewer: "Viewer" } satisfies Record<Role, string>,
  joinedAt: (date: string) => `Joined ${date}`,

  joinTitle: "Join a room",
  joinIntro: "Enter the invite code you received from the host.",
  inviteCode: "Invite code",
  inviteCodeHint: "12 letters and digits, for example ABCD-EFGH-JK23.",
  inviteCodeInvalid:
    "That doesn't look like an invite code. Check it has 12 letters and digits (no I, O, 0 or 1).",
  joiningAs: (name: string) => `You'll join as ${name}.`,
  join: "Join",
  joining: "Joining…",
  cancel: "Cancel",

  room: "Room",
  inviteCodeLabel: "Invite code",
  inviteShare: "Share this code and, if you set one, the room password.",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Couldn't copy. Select the code and copy it manually.",
  noInviteCode: "Only the host can see the invite code.",
  leave: "Leave room",
  backToLobby: "Back to lobby",
  status: {
    connecting: "Connecting…",
    syncing: "Syncing project…",
    connected: "Connected",
    reconnecting: "Connection lost. Reconnecting…",
    closed: "Disconnected",
  } satisfies Record<CollabStatus, string>,
  closeReasons: {
    left: "You left the room.",
    kicked: "You were removed by the host.",
    "room-closed": "The host closed this room.",
    "session-replaced": "This room was opened in another window. This window will stay offline.",
    unauthorized: "Your invite is no longer valid. Ask the host for a new code.",
    error: "The connection failed. Try joining again.",
  } satisfies Record<CollabCloseReason, string>,
  people: "People",
  peopleCount: (online: number, total: number) => `${online} online · ${total} total`,
  you: "(you)",
  online: "Online",
  offline: "Offline",
  makeViewer: "Make viewer",
  makeEditor: "Make editor",
  changeRoleLabel: (name: string, role: string) => `Change ${name} to ${role}`,
  remove: "Remove",
  removeLabel: (name: string) => `Remove ${name} from the room`,
  removeTitle: (name: string) => `Remove ${name}?`,
  removeIntro: "They will be disconnected from this room.",
  noParticipants: "Waiting for others to join…",
  chipLabel: (status: string, online: number) =>
    `Collaboration: ${status}, ${online} ${online === 1 ? "person" : "people"} online. Open collaboration panel`,
  chipIdleLabel: "Collaboration. Open collaboration panel",
  chipName: "Collaborate",
  /** Short toolbar labels; the full status is in the chip's accessible name and tooltip. */
  chipStatus: {
    connecting: "Connecting",
    syncing: "Syncing",
    connected: "Collaborate",
    reconnecting: "Reconnecting",
    closed: "Offline",
  } satisfies Record<CollabStatus, string>,
  chipUnread: (count: number) => `${count} unread ${count === 1 ? "message" : "messages"}`,
  chipRequests: (count: number) => `${count} control ${count === 1 ? "request" : "requests"}`,
  chipJoin: (parts: readonly string[]) => parts.join(", "),

  chat: {
    log: "Chat messages",
    empty: "No messages yet. Say hello to your team.",
    you: "You",
    input: "Message",
    placeholder: "Message the room (Enter to send, Shift+Enter for a new line)",
    send: "Send",
    sending: "Sending…",
    justNow: "just now",
    today: "Today",
    yesterday: "Yesterday",
    newMessages: "View new messages",
    newMessagesLabel: (count: number) =>
      `View ${count} new ${count === 1 ? "message" : "messages"}`,
    tooLong: "Message is too long.",
    blocked: {
      closed: "You have left this room. Chat history is read-only.",
      offline: "Not connected. Your draft is kept and can be sent once the connection is back.",
      syncing: "Syncing the room. You can send once it finishes; your draft is kept.",
      viewer: "Viewers can read the chat but can't send messages in this room.",
    } satisfies Record<ChatSendBlock, string>,
    sendNetwork: "Could not send. Check your connection; your draft is kept.",
    sendRateLimited: "You're sending messages too quickly. Wait a moment and try again.",
    sendRejected: (reason: string) => `Could not send. ${reason} Your draft is kept.`,
    draftSaveFailed: "Could not save this draft. Retry; the text is kept in this window.",
    draftPrepareFailed: "Could not save the draft. Please retry.",
    draftUpdateFailed:
      "Message sent, but the local draft could not be updated. Retry saving before quitting.",
  },

  errors: {
    "room-closed": "This room has been ended. Create a new room from your retained project.",
    removed: "Your room access was revoked. Ask the host for a new invitation.",
    "identity-missing":
      "This room has no saved recovery credential. Open your retained project to create a new room.",
    network: "Can't reach the collaboration service. Check your internet connection.",
    unavailable: "Collaboration isn't available right now. Try again later.",
    "not-found": "No room matches that invite code. Check the code and try again.",
    "room-full": "This room is full.",
    "rate-limited": "Too many attempts. Wait a minute and try again.",
    expired: "This invite has expired. Ask the host for a new code.",
    "bad-request": "The request was invalid. Check the details and try again.",
    unauthorized: "You're not allowed to do that. Try joining the room again.",
    "password-required": "This room requires a password. Ask the host for it.",
    "invalid-password": "The room password is incorrect. Try again.",
    forbidden: "Only the host can do that.",
    internal: "The collaboration service had a problem. Try again later.",
  } satisfies Record<CollabErrorCode, string>,
  unknownError: "Something went wrong. Try again.",
};

export type CollabCopy = typeof en;

const zhTW: CollabCopy = {
  lobbyTitle: "一起協作",
  lobbyIntro: "與同學或隊友共享專案，所有人即時編輯同一份檔案。",
  displayName: "你的顯示名稱",
  displayNameHint: "房間內的所有人都會看到這個名稱。",
  displayNameProblems: {
    empty: "請輸入顯示名稱，才能建立或加入房間。",
    "too-long": "名稱最多 40 個字元。",
    invalid: "名稱不可包含控制字元。",
  },
  startRoom: "建立房間",
  startHint: (project) => `邀請其他人編輯「${project}」。`,
  startNeedsProject: "請先開啟專案，才能建立房間。",
  starting: "正在建立房間…",
  createIntro: "透過邀請碼加入的人將能存取此專案的檔案。",
  roomPassword: "房間密碼（選填）",
  createPasswordHint: "留空時，其他人只需邀請碼即可加入。",
  joinPasswordHint: "若主持人有設定密碼，請在此輸入。應用程式不會記住密碼。",
  hostingAs: (name) => `你將以「${name}」的身分主持房間。`,
  joinRoom: "加入房間",
  joinHint: "有邀請碼嗎？加入別人的專案。",
  recentRooms: "最近的房間",
  noRecentRooms: "你建立或加入的房間會顯示在這裡。",
  rejoin: "重新加入",
  roles: { host: "主持人", editor: "編輯者", viewer: "檢視者" },
  joinedAt: (date) => `加入於 ${date}`,

  joinTitle: "加入房間",
  joinIntro: "輸入主持人提供的邀請碼。",
  inviteCode: "邀請碼",
  inviteCodeHint: "12 個英文字母與數字，例如 ABCD-EFGH-JK23。",
  inviteCodeInvalid: "邀請碼格式不正確。請確認共有 12 個英文字母與數字（不含 I、O、0、1）。",
  joiningAs: (name) => `你將以「${name}」的身分加入。`,
  join: "加入",
  joining: "正在加入…",
  cancel: "取消",

  room: "房間",
  inviteCodeLabel: "邀請碼",
  inviteShare: "分享此邀請碼；若有設定房間密碼，請一併告知對方。",
  copy: "複製",
  copied: "已複製",
  copyFailed: "無法複製，請手動選取並複製邀請碼。",
  noInviteCode: "只有主持人可以看到邀請碼。",
  leave: "離開房間",
  backToLobby: "返回大廳",
  status: {
    connecting: "正在連線…",
    syncing: "正在同步專案…",
    connected: "已連線",
    reconnecting: "連線中斷，正在重新連線…",
    closed: "已中斷連線",
  },
  closeReasons: {
    left: "你已離開房間。",
    kicked: "你已被主持人移出房間。",
    "room-closed": "主持人已關閉此房間。",
    "session-replaced": "此身分已在另一個視窗連線，本視窗已停止重連。",
    unauthorized: "你的邀請已失效，請向主持人索取新的邀請碼。",
    error: "連線失敗，請重新加入。",
  },
  people: "成員",
  peopleCount: (online, total) => `${online} 人在線 · 共 ${total} 人`,
  you: "（你）",
  online: "在線",
  offline: "離線",
  makeViewer: "設為檢視者",
  makeEditor: "設為編輯者",
  changeRoleLabel: (name, role) => `將 ${name} 改為${role}`,
  remove: "移除",
  removeLabel: (name) => `將 ${name} 移出房間`,
  removeTitle: (name) => `要移除 ${name} 嗎？`,
  removeIntro: "對方將被中斷與此房間的連線。",
  noParticipants: "正在等待其他人加入…",
  chipLabel: (status, online) => `協作：${status}，${online} 人在線。開啟協作面板`,
  chipIdleLabel: "協作。開啟協作面板",
  chipName: "協作",
  chipStatus: {
    connecting: "連線中",
    syncing: "同步中",
    connected: "協作",
    reconnecting: "重新連線中",
    closed: "離線",
  },
  chipUnread: (count) => `${count} 則未讀訊息`,
  chipRequests: (count) => `${count} 個控制權請求`,
  chipJoin: (parts) => parts.join("，"),

  chat: {
    log: "聊天訊息",
    empty: "還沒有訊息，向大家打個招呼吧。",
    you: "你",
    input: "訊息",
    placeholder: "傳送訊息給房間成員（Enter 傳送，Shift+Enter 換行）",
    send: "傳送",
    sending: "傳送中…",
    justNow: "剛剛",
    today: "今天",
    yesterday: "昨天",
    newMessages: "查看新訊息",
    newMessagesLabel: (count) => `查看 ${count} 則新訊息`,
    tooLong: "訊息太長。",
    blocked: {
      closed: "你已離開房間，聊天紀錄僅供閱讀。",
      offline: "目前未連線。草稿會保留，恢復連線後即可傳送。",
      syncing: "正在同步房間，完成後即可傳送；草稿會保留。",
      viewer: "檢視者可以閱讀聊天，但無法在此房間傳送訊息。",
    },
    sendNetwork: "傳送失敗，請檢查網路連線；草稿已保留。",
    sendRateLimited: "傳送太頻繁，請稍候再試。",
    sendRejected: (reason) => `傳送失敗。${reason}草稿已保留。`,
    draftSaveFailed: "無法保存聊天草稿，請重試；內容會保留在此視窗。",
    draftPrepareFailed: "無法保存草稿，請重試。",
    draftUpdateFailed: "訊息已傳送，但無法更新本機草稿。退出前請重試保存。",
  },

  errors: {
    "room-closed": "房間已結束。可以保留的專案建立新房間。",
    removed: "你的房間存取權已撤銷，請向主持人取得新的邀請。",
    "identity-missing": "此房間沒有保存恢復憑證。請開啟保留的專案並建立新房間。",
    network: "無法連線到協作服務，請檢查網路連線。",
    unavailable: "協作功能目前無法使用，請稍後再試。",
    "not-found": "找不到符合此邀請碼的房間，請確認後再試一次。",
    "room-full": "此房間已滿。",
    "rate-limited": "嘗試次數過多，請稍候一分鐘再試。",
    expired: "此邀請已過期，請向主持人索取新的邀請碼。",
    "bad-request": "要求無效，請確認內容後再試一次。",
    unauthorized: "你沒有權限執行此操作，請重新加入房間。",
    "password-required": "此房間需要密碼，請向主持人索取。",
    "invalid-password": "房間密碼不正確，請再試一次。",
    forbidden: "只有主持人可以執行此操作。",
    internal: "協作服務發生問題，請稍後再試。",
  },
  unknownError: "發生錯誤，請再試一次。",
};

export const collabCopy: Record<Locale, CollabCopy> = { en, "zh-TW": zhTW };

export function collabErrorMessage(
  copy: CollabCopy,
  error: CollabErrorCode | "unknown" | undefined,
): string {
  return (error && error !== "unknown" && copy.errors[error]) || copy.unknownError;
}
