export type Locale = "en" | "zh-TW";
export const copy = {
  en: {
    runOnDevice: "Run on EV3",
    advanced: "More actions",
    lightTheme: "Light theme",
    darkTheme: "Dark theme",
    workspace: "Your robot’s workbench",
    welcomeNote: "BASIC PLUS / EV3 NATIVE",
    editStep: "Write your idea",
    editHint: "Start a project and make it your own with Basic Plus.",
    connectStep: "Connect your EV3",
    connectHint: "Use a USB cable or connect over your local Wi-Fi.",
    runStep: "Make it move",
    runHint: "Save, build and upload with one click. See every step.",
    offline: "Local projects. Native programs. Ready offline.",
    activity: "Activity",
    noActivity: "Build and device operations will appear here.",
    usbHint: "Connect your EV3 with a USB cable, then search for devices.",
    wifiHint: "Use a discovered EV3 or enter its address on the same network.",
    connectionHint: "Choose how to connect. Your program stays on this computer until you run it.",
    connectionRequired: "Connect an EV3 to continue this run.",
    connectionReady: "Connected and ready to receive your program.",
    uploadLatest: "Upload successful build",
    runUploaded: "Run uploaded version",
    deleteUploaded: "Delete uploaded program",
    latestBuild: "Successful build",
    deployedVersion: "Uploaded version",
    noBuild: "No successful build yet",
    noUpload: "No program uploaded in this session",
    errorHint: "Review the details below, correct the problem, then try again.",
    reconnectHint: "Check the EV3 connection, reconnect, then try again.",
    details: "Details",
    locked: "Editing is paused while this operation completes.",
    mode: "Connection method",
    closePanel: "Close EV3 panel",
    phases: {
      idle: "Ready",
      awaitingDevice: "Waiting for EV3",
      connecting: "Connecting…",
      saving: "Saving all changes…",
      building: "Building…",
      uploading: "Uploading program and assets…",
      running: "Sending run command…",
      stopping: "Sending stop command…",
      deleting: "Deleting uploaded program…",
      disconnecting: "Disconnecting…",
      error: "Operation failed",
    },
    messages: {
      files: "EV3 files",
      idle: "Ready",
      awaitingDevice: "Connect EV3 to continue",
      connecting: "Connecting to EV3",
      saving: "Saving all changes",
      building: "Building program",
      uploading: "Uploading program and assets",
      running: "Sending run command",
      stopping: "Sending stop command",
      deleting: "Deleting uploaded program",
      disconnecting: "Disconnecting EV3",
      error: "Operation failed",
      built: "Build complete",
      uploaded: "Program and assets uploaded",
      runSent: "Run command sent",
      stopped: "Stop command sent",
      deleted: "Uploaded program deleted",
      connected: "EV3 connected",
      disconnected: "EV3 disconnected",
      cancelled: "Operation cancelled",
    },
    connectionStates: {
      disconnected: "Not connected",
      connected: "Connected",
      connecting: "Connecting",
      busy: "Busy",
      error: "Connection failed",
    },

    newProject: "New project",
    open: "Open",
    save: "Save",
    build: "Build",
    cancel: "Cancel",
    welcome: "Build ideas that move",
    intro: "Open a Basic Plus program or create a small EV3 project to begin.",
    files: "Project",
    diagnostics: "Diagnostics",
    devices: "EV3 device",
    discover: "Find EV3",
    connect: "Connect",
    disconnect: "Disconnect",
    upload: "Upload",
    run: "Run",
    stop: "Stop",
    remove: "Delete",
    address: "Wi-Fi address",
    noProblems: "No problems found.",
    ready: "Ready",
    selectDevice: "Select a discovered EV3",
    candidate: "v1 candidate",
    projectName: "Project name",
    projectNameHint: "Letters, numbers, dashes and underscores",
    create: "Create project",
    chooseEntry: "Choose entry file",
    continue: "Continue",
    close: "Cancel",
    format: "Format",
    previousProblem: "Previous problem",
    nextProblem: "Next problem",
    showFiles: "Show project",
    hideFiles: "Hide project",
    showDevice: "Show EV3 panel",
    hideDevice: "Hide EV3 panel",
    showProblems: "Show diagnostics",
    hideProblems: "Hide diagnostics",
    closeTab: "Close tab",
    unsavedTitle: "Save changes before closing?",
    unsavedBody: (file: string) => `${file} has changes that have not been saved to the project.`,
    saveAndClose: "Save and close",
    discardAndClose: "Discard changes",
    checking: "Checking…",
    errors: "errors",
    warnings: "warnings",
    chooseFile: "Choose a project file",
    saved: "Saved",
    unsaved: "Unsaved changes",
    editorLabel: "Code editor",
    line: "Ln",
    column: "Col",
    basicPlus: "BASIC PLUS",
    buildComplete: "Build complete",
    buildFailed: "Build failed",
    startingBuild: "Starting build…",
    savedStatus: "Saved",
    choosingLocation: "Choose a project location…",
    searching: "Searching for EV3…",
    devicesFound: (count: number) => `Found ${count} EV3 device(s)`,
    noDevice: "No EV3 found",
    actionComplete: (action: string) => `${action} complete`,
    resizeFiles: "Resize project panel",
    resizeDevice: "Resize EV3 panel",
    resizeProblems: "Resize diagnostics panel",
    fileTree: "Project files",
    newFile: "New file",
    newFolder: "New folder",
    moreActions: "More file actions",
    rename: "Rename",
    move: "Move…",
    moveTitle: "Move project item",
    moveDestination: "Destination folder",
    trash: "Move to Trash",
    trashTitle: "Move this item to Trash?",
    trashBody: (entry: string) => `${entry} will be removed from this project and moved to Trash.`,
    trashDirty: "Open unsaved changes inside it will be discarded.",
    entryName: "Name",
    entryParent: "Location",
    createFileTitle: "Create file",
    createFolderTitle: "Create folder",
    createEntryAction: "Create",
    expand: "Expand",
    collapse: "Collapse",
    manifestDirty: "Save or discard kobrixa.json changes before moving the build entry.",
    managingFiles: "Updating project files…",
  },
  "zh-TW": {
    runOnDevice: "在 EV3 執行",
    advanced: "更多操作",
    lightTheme: "淺色主題",
    darkTheme: "深色主題",
    workspace: "你的機器人工作台",
    welcomeNote: "BASIC PLUS / EV3 NATIVE",
    editStep: "寫下你的想法",
    editHint: "建立專案，用 Basic Plus 把創意化成程式。",
    connectStep: "連接你的 EV3",
    connectHint: "接上 USB 線，或透過區域 Wi-Fi 建立連線。",
    runStep: "讓它動起來",
    runHint: "一鍵儲存、建置並上傳，每個步驟都清楚可見。",
    offline: "本機專案・原生程式・離線也能創作",
    activity: "操作紀錄",
    noActivity: "建置與裝置操作的結果會顯示在這裡。",
    usbHint: "使用 USB 線連接 EV3，然後搜尋裝置。",
    wifiHint: "選擇搜尋到的 EV3，或輸入同一網路內的裝置位址。",
    connectionHint: "選擇連線方式；執行前，程式會保留在這部電腦上。",
    connectionRequired: "連接 EV3 後，將接續這次執行。",
    connectionReady: "已連線，可以上傳你的程式。",
    uploadLatest: "上傳成功建置",
    runUploaded: "執行已上傳版本",
    deleteUploaded: "刪除已上傳程式",
    latestBuild: "成功建置",
    deployedVersion: "已上傳版本",
    noBuild: "尚無成功建置",
    noUpload: "本次連線尚未上傳程式",
    errorHint: "查看下方詳細資訊，修正問題後再試一次。",
    reconnectHint: "檢查 EV3 連線，重新連接後再試一次。",
    details: "詳細資訊",
    locked: "操作期間暫停編輯，完成後即可繼續。",
    mode: "連線方式",
    closePanel: "關閉 EV3 面板",
    phases: {
      idle: "就緒",
      awaitingDevice: "等待 EV3 連線",
      connecting: "正在連線…",
      saving: "正在儲存全部修改…",
      building: "正在建置…",
      uploading: "正在上傳程式與素材…",
      running: "正在送出執行指令…",
      stopping: "正在送出停止指令…",
      deleting: "正在刪除已上傳程式…",
      disconnecting: "正在中斷連線…",
      error: "操作失敗",
    },
    messages: {
      files: "EV3 檔案",
      idle: "就緒",
      awaitingDevice: "連接 EV3 以繼續",
      connecting: "正在連接 EV3",
      saving: "正在儲存全部修改",
      building: "正在建置程式",
      uploading: "正在上傳程式與素材",
      running: "正在送出執行指令",
      stopping: "正在送出停止指令",
      deleting: "正在刪除已上傳程式",
      disconnecting: "正在中斷 EV3 連線",
      error: "操作失敗",
      built: "建置完成",
      uploaded: "程式與素材已上傳",
      runSent: "已送出執行指令",
      stopped: "已送出停止指令",
      deleted: "已刪除上傳的程式",
      connected: "EV3 已連線",
      disconnected: "EV3 已中斷連線",
      cancelled: "操作已取消",
    },
    connectionStates: {
      disconnected: "未連線",
      connected: "已連線",
      connecting: "連線中",
      busy: "忙碌中",
      error: "連線失敗",
    },

    newProject: "建立專案",
    open: "開啟",
    save: "儲存",
    build: "建置",
    cancel: "取消",
    welcome: "讓創意真正動起來",
    intro: "開啟 Basic Plus 程式，或建立一個 EV3 小專案開始使用。",
    files: "專案",
    diagnostics: "診斷",
    devices: "EV3 裝置",
    discover: "搜尋 EV3",
    connect: "連線",
    disconnect: "中斷",
    upload: "上傳",
    run: "執行",
    stop: "停止",
    remove: "刪除",
    address: "Wi-Fi 位址",
    noProblems: "沒有發現問題。",
    ready: "就緒",
    selectDevice: "選擇搜尋到的 EV3",
    candidate: "v1 候選版",
    projectName: "專案名稱",
    projectNameHint: "可使用英文字母、數字、連字號與底線",
    create: "建立專案",
    chooseEntry: "選擇進入點檔案",
    continue: "繼續",
    close: "取消",
    format: "格式化",
    previousProblem: "上一個問題",
    nextProblem: "下一個問題",
    showFiles: "顯示專案",
    hideFiles: "隱藏專案",
    showDevice: "顯示 EV3 面板",
    hideDevice: "隱藏 EV3 面板",
    showProblems: "顯示診斷",
    hideProblems: "隱藏診斷",
    closeTab: "關閉分頁",
    unsavedTitle: "關閉前要儲存變更嗎？",
    unsavedBody: (file: string) => `${file} 的變更尚未儲存到專案。`,
    saveAndClose: "儲存並關閉",
    discardAndClose: "捨棄變更",
    checking: "檢查中…",
    errors: "錯誤",
    warnings: "警告",
    chooseFile: "選擇專案檔案",
    saved: "已儲存",
    unsaved: "有未儲存變更",
    editorLabel: "程式碼編輯器",
    line: "行",
    column: "列",
    basicPlus: "BASIC PLUS",
    buildComplete: "建置完成",
    buildFailed: "建置失敗",
    startingBuild: "正在開始建置…",
    savedStatus: "已儲存",
    choosingLocation: "選擇專案存放位置…",
    searching: "正在搜尋 EV3…",
    devicesFound: (count: number) => `找到 ${count} 部 EV3 裝置`,
    noDevice: "找不到 EV3",
    actionComplete: (action: string) => `${action} 完成`,
    resizeFiles: "調整專案面板寬度",
    resizeDevice: "調整 EV3 面板寬度",
    resizeProblems: "調整診斷面板高度",
    fileTree: "專案檔案",
    newFile: "新增檔案",
    newFolder: "新增資料夾",
    moreActions: "更多檔案操作",
    rename: "重新命名",
    move: "移動…",
    moveTitle: "移動專案項目",
    moveDestination: "目的資料夾",
    trash: "移到垃圾桶",
    trashTitle: "要將此項目移到垃圾桶嗎？",
    trashBody: (entry: string) => `${entry} 將從專案移除並移到系統垃圾桶。`,
    trashDirty: "其中已開啟但尚未儲存的變更將被捨棄。",
    entryName: "名稱",
    entryParent: "位置",
    createFileTitle: "新增檔案",
    createFolderTitle: "新增資料夾",
    createEntryAction: "建立",
    expand: "展開",
    collapse: "收合",
    manifestDirty: "移動建置入口前，請先儲存或捨棄 kobrixa.json 的變更。",
    managingFiles: "正在更新專案檔案…",
  },
} as const;

export type Copy = (typeof copy)[Locale];
