export const remoteCopy = {
  en: {
    files: "EV3 files",
    root: "Projects",
    ancestors: "Parent folders",
    up: "Up one folder",
    refresh: "Refresh",
    upload: "Upload",
    uploadFiles: "Choose files…",
    uploadFolders: "Choose folders…",
    mkdir: "New folder",
    download: "Download",
    remove: "Delete",
    rename: "Rename",
    clear: "Clear selection",
    search: "Search this folder",
    selected: "selected",
    selectAll: "Select visible items",
    hiddenSelected: "hidden by search",
    items: "items",
    file: "File",
    folder: "Folder",
    storage: "Storage",
    open: "Open folder",
    empty: "This folder is empty.",
    noMatch: "No matching items.",
    clearSearch: "Clear search",
    disconnected: "Connect your EV3 to browse its files.",
    connect: "Open connection",
    idle: "Click a row to select it; use the folder button to open it.",
    failed: "Operation failed",
    refreshFailed: "The operation result is kept, but the folder could not be refreshed.",
    permission: "EV3 denied access to this location.",
    missing: "The requested item no longer exists. Your current folder is kept.",
    interrupted: "The connection or transfer was interrupted.",
    generic: "Check the details before trying again. Changes are never retried automatically.",
    details: "Details",
    retry: "Read folder again",
    busy: "Another EV3 operation is in progress.",
    name: "Name",
    cancel: "Cancel",
    apply: "Apply",
    renameHint: "Copies and verifies the contents before removing the source.",
    nameHint: "Use letters, numbers, spaces, underscores or hyphens.",
    checking: "Checking items…",
    ready: "Ready for review",
    running: "Working…",
    complete: "Completed",
    stopped: "Stopped",
    cancelled: "Cancelled",
    uploadAction: "Uploading",
    downloadAction: "Downloading",
    deleteAction: "Deleting",
    listAction: "Reading folder…",
    mkdirAction: "Creating folder…",
    renameAction: "Renaming…",
    refreshing: "Updating folder…",
    stop: "Stop after current item",
    stopping: "Stopping after current item…",
    cancelCheck: "Cancel preparation",
    review: "Review operation",
    dismiss: "Dismiss results",
    results: "Item results",
    succeeded: "Succeeded",
    skipped: "Skipped",
    pending: "Not processed",
    failedItem: "Failed",
    runningItem: "In progress",
    conflicts: "Existing files",
    bytesKnown: "Known file size",
    replace: "Replace all existing files",
    skip: "Skip all existing files",
    merge: "Folders with the same name will be merged. Other destination contents are kept.",
    deleteWarning: "Permanently delete these items? Selected folders include all their contents.",
    confirm: "Start transfer",
    confirmDelete: "Delete selected items",
    deleteCount: (files: number, folders: number) =>
      `${files} file${files === 1 ? "" : "s"} · ${folders} folder${folders === 1 ? "" : "s"}`,
    partial: "Completed items are kept. No changes have been rolled back.",
    uploadPartial:
      "A failed upload may leave an incomplete file on the EV3. Check it before retrying.",
    checkFailed: "Preparation failed. Nothing was written.",
    select: "Select",
    stopHint: "The current transfer or recursive deletion finishes before stopping.",
  },
  "zh-TW": {
    files: "EV3 檔案",
    root: "專案區",
    ancestors: "上層資料夾",
    up: "上一層",
    refresh: "重新整理",
    upload: "上傳",
    uploadFiles: "選取檔案…",
    uploadFolders: "選取資料夾…",
    mkdir: "新增資料夾",
    download: "下載",
    remove: "刪除",
    rename: "重新命名",
    clear: "清除選取",
    search: "搜尋目前資料夾",
    selected: "項已選取",
    selectAll: "全選目前結果",
    hiddenSelected: "項被搜尋隱藏",
    items: "項目",
    file: "檔案",
    folder: "資料夾",
    storage: "儲存區",
    open: "開啟資料夾",
    empty: "此資料夾沒有內容。",
    noMatch: "沒有符合的項目。",
    clearSearch: "清除搜尋",
    disconnected: "連線 EV3 後，即可瀏覽裝置檔案。",
    connect: "開啟連線頁",
    idle: "點整列勾選；使用資料夾按鈕開啟。",
    failed: "操作失敗",
    refreshFailed: "操作結果已保留，但無法更新資料夾清單。",
    permission: "EV3 不允許存取此位置。",
    missing: "要求的項目已不存在，目前資料夾保持不變。",
    interrupted: "連線或傳輸已中斷。",
    generic: "請先檢查詳細資訊再重試，不會自動重做修改。",
    details: "詳細資訊",
    retry: "重新讀取資料夾",
    busy: "其他 EV3 操作正在進行。",
    name: "名稱",
    cancel: "取消",
    apply: "套用",
    renameHint: "先複製並核對內容，再刪除來源。",
    nameHint: "請使用英文字母、數字、空格、底線或連字號。",
    checking: "正在檢查項目…",
    ready: "等待確認",
    running: "正在處理…",
    complete: "已完成",
    stopped: "已停止",
    cancelled: "已取消",
    uploadAction: "正在上傳",
    downloadAction: "正在下載",
    deleteAction: "正在刪除",
    listAction: "正在讀取資料夾…",
    mkdirAction: "正在建立資料夾…",
    renameAction: "正在重新命名…",
    refreshing: "正在更新清單…",
    stop: "完成目前項目後停止",
    stopping: "將在目前項目完成後停止…",
    cancelCheck: "取消預檢",
    review: "檢查操作內容",
    dismiss: "收起結果",
    results: "逐項結果",
    succeeded: "成功",
    skipped: "略過",
    pending: "未執行",
    failedItem: "失敗",
    runningItem: "處理中",
    conflicts: "同名檔案",
    bytesKnown: "已知檔案大小",
    replace: "覆寫全部同名檔案",
    skip: "略過全部同名檔案",
    merge: "同名資料夾會合併，保留目標中其他內容。",
    deleteWarning: "永久刪除以下項目？所選資料夾包含其所有內容。",
    confirm: "開始傳輸",
    confirmDelete: "刪除所選項目",
    deleteCount: (files: number, folders: number) => `${files} 個檔案 · ${folders} 個資料夾`,
    partial: "已完成的項目會保留，沒有回復任何已完成的修改。",
    uploadPartial: "上傳失敗可能在 EV3 留下不完整檔案，重試前請先確認。",
    checkFailed: "預檢未通過，尚未寫入任何項目。",
    select: "選取",
    stopHint: "目前的傳輸或遞迴刪除會完成後才停止。",
  },
};
export type RemoteCopy = (typeof remoteCopy)[keyof typeof remoteCopy];
export function formatSize(bytes: number): string {
  return bytes < 1024
    ? `${bytes} B`
    : bytes < 1024 * 1024
      ? `${(bytes / 1024).toFixed(1)} KB`
      : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
